version: '3.9'

services:
  tdd-services:
    build: .
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000 --workers 1
    ports:
      - 8000:8000
    environment:
      - ENVIRONMENT=dev
      - TESTING=0